# Generated by Django 2.2.5 on 2019-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_studentprofileinfo_jlt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='jlt',
            field=models.CharField(default='i am sai', max_length=100),
        ),
    ]
