# Generated by Django 2.2.5 on 2019-12-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20191217_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofileinfo',
            name='roll',
            field=models.CharField(default='17261A0551', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='profile_pics_students'),
        ),
    ]
