# Generated by Django 2.2.5 on 2019-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20191217_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepassrequests',
            name='roll',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
