# Generated by Django 2.2.5 on 2019-12-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20191217_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepassrequests',
            name='date',
        ),
        migrations.AddField(
            model_name='gatepassrequests',
            name='branch',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='gatepassrequests',
            name='status',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
