# Generated by Django 2.2.5 on 2019-12-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20191218_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepassrequests',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('R', 'R'), ('A', 'A'), ('O', 'O')], max_length=3),
        ),
    ]
