# Generated by Django 2.2.5 on 2019-12-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_auto_20191218_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGatepassRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, max_length=10)),
                ('branch', models.CharField(blank=True, max_length=5)),
                ('status', models.CharField(blank=True, choices=[('Denied', 'Denied'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('OutOfColloge', 'OutOfColloge'), ('NotRequested', 'NotRequested')], default='NotRequested', max_length=15)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
    ]
